# 应用服务 WEB 访问端口
server:
  port:
    8088

spring:
  # 设置上传文件的大小
  servlet:
    multipart:
      max-file-size: 10MB
  # 应用名称
  application:
    name:
      onlineFile
  # 数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinefile?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 100ms
    database: 1


